/* tslint:disable */
/* eslint-disable */
/**
 * Cash CMS API
 * Cash CMS API.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@cashcms.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CashcmsUser
 */
export interface CashcmsUser {
    /**
     * 
     * @type {string}
     * @memberof CashcmsUser
     */
    balance?: string;
    /**
     * 
     * @type {Date}
     * @memberof CashcmsUser
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof CashcmsUser
     */
    deletedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof CashcmsUser
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof CashcmsUser
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof CashcmsUser
     */
    role?: string;
    /**
     * 
     * @type {Date}
     * @memberof CashcmsUser
     */
    updatedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof CashcmsUser
     */
    username?: string;
}

/**
 * Check if a given object implements the CashcmsUser interface.
 */
export function instanceOfCashcmsUser(value: object): boolean {
    return true;
}

export function CashcmsUserFromJSON(json: any): CashcmsUser {
    return CashcmsUserFromJSONTyped(json, false);
}

export function CashcmsUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): CashcmsUser {
    if (json == null) {
        return json;
    }
    return {
        
        'balance': json['balance'] == null ? undefined : json['balance'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'deletedAt': json['deletedAt'] == null ? undefined : (new Date(json['deletedAt'])),
        'email': json['email'] == null ? undefined : json['email'],
        'id': json['id'] == null ? undefined : json['id'],
        'role': json['role'] == null ? undefined : json['role'],
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'username': json['username'] == null ? undefined : json['username'],
    };
}

export function CashcmsUserToJSON(value?: CashcmsUser | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'balance': value['balance'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'deletedAt': value['deletedAt'] == null ? undefined : ((value['deletedAt']).toISOString()),
        'email': value['email'],
        'id': value['id'],
        'role': value['role'],
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
        'username': value['username'],
    };
}

