/* tslint:disable */
/* eslint-disable */
/**
 * Cash CMS API
 * Cash CMS API.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@cashcms.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CashcmsCredentials } from './CashcmsCredentials';
import {
    CashcmsCredentialsFromJSON,
    CashcmsCredentialsFromJSONTyped,
    CashcmsCredentialsToJSON,
} from './CashcmsCredentials';

/**
 * 
 * @export
 * @interface CashcmsUploadCredits
 */
export interface CashcmsUploadCredits {
    /**
     * 存储桶名
     * @type {string}
     * @memberof CashcmsUploadCredits
     */
    bucket?: string;
    /**
     * 临时证书
     * @type {CashcmsCredentials}
     * @memberof CashcmsUploadCredits
     */
    credentials?: CashcmsCredentials;
    /**
     * 证书有效的时间，以 iso8601 格式的 UTC 时间表示
     * 注意：此字段可能返回 null，表示取不到有效值。
     * @type {string}
     * @memberof CashcmsUploadCredits
     */
    expiration?: string;
    /**
     * 临时证书有效的时间，返回 Unix 时间戳，精确到秒
     * @type {number}
     * @memberof CashcmsUploadCredits
     */
    expiredTime?: number;
    /**
     * 区域
     * @type {string}
     * @memberof CashcmsUploadCredits
     */
    region?: string;
}

/**
 * Check if a given object implements the CashcmsUploadCredits interface.
 */
export function instanceOfCashcmsUploadCredits(value: object): boolean {
    return true;
}

export function CashcmsUploadCreditsFromJSON(json: any): CashcmsUploadCredits {
    return CashcmsUploadCreditsFromJSONTyped(json, false);
}

export function CashcmsUploadCreditsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CashcmsUploadCredits {
    if (json == null) {
        return json;
    }
    return {
        
        'bucket': json['bucket'] == null ? undefined : json['bucket'],
        'credentials': json['credentials'] == null ? undefined : CashcmsCredentialsFromJSON(json['credentials']),
        'expiration': json['expiration'] == null ? undefined : json['expiration'],
        'expiredTime': json['expiredTime'] == null ? undefined : json['expiredTime'],
        'region': json['region'] == null ? undefined : json['region'],
    };
}

export function CashcmsUploadCreditsToJSON(value?: CashcmsUploadCredits | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'bucket': value['bucket'],
        'credentials': CashcmsCredentialsToJSON(value['credentials']),
        'expiration': value['expiration'],
        'expiredTime': value['expiredTime'],
        'region': value['region'],
    };
}

