/* tslint:disable */
/* eslint-disable */
/**
 * Cash CMS API
 * Cash CMS API.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@cashcms.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CashcmsCategory
 */
export interface CashcmsCategory {
    /**
     * 
     * @type {Date}
     * @memberof CashcmsCategory
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof CashcmsCategory
     */
    deletedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof CashcmsCategory
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof CashcmsCategory
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof CashcmsCategory
     */
    title?: string;
    /**
     * 
     * @type {Date}
     * @memberof CashcmsCategory
     */
    updatedAt?: Date;
}

/**
 * Check if a given object implements the CashcmsCategory interface.
 */
export function instanceOfCashcmsCategory(value: object): boolean {
    return true;
}

export function CashcmsCategoryFromJSON(json: any): CashcmsCategory {
    return CashcmsCategoryFromJSONTyped(json, false);
}

export function CashcmsCategoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): CashcmsCategory {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'deletedAt': json['deletedAt'] == null ? undefined : (new Date(json['deletedAt'])),
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'title': json['title'] == null ? undefined : json['title'],
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
    };
}

export function CashcmsCategoryToJSON(value?: CashcmsCategory | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'deletedAt': value['deletedAt'] == null ? undefined : ((value['deletedAt']).toISOString()),
        'id': value['id'],
        'name': value['name'],
        'title': value['title'],
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
    };
}

