/* tslint:disable */
/* eslint-disable */
/**
 * Cash CMS API
 * Cash CMS API.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@cashcms.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CashcmsPaymentMethod
 */
export interface CashcmsPaymentMethod {
    /**
     * 
     * @type {string}
     * @memberof CashcmsPaymentMethod
     */
    displayName?: string;
    /**
     * 
     * @type {string}
     * @memberof CashcmsPaymentMethod
     */
    icon?: string;
    /**
     * 
     * @type {string}
     * @memberof CashcmsPaymentMethod
     */
    name?: string;
}

/**
 * Check if a given object implements the CashcmsPaymentMethod interface.
 */
export function instanceOfCashcmsPaymentMethod(value: object): boolean {
    return true;
}

export function CashcmsPaymentMethodFromJSON(json: any): CashcmsPaymentMethod {
    return CashcmsPaymentMethodFromJSONTyped(json, false);
}

export function CashcmsPaymentMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): CashcmsPaymentMethod {
    if (json == null) {
        return json;
    }
    return {
        
        'displayName': json['displayName'] == null ? undefined : json['displayName'],
        'icon': json['icon'] == null ? undefined : json['icon'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function CashcmsPaymentMethodToJSON(value?: CashcmsPaymentMethod | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'displayName': value['displayName'],
        'icon': value['icon'],
        'name': value['name'],
    };
}

