/* tslint:disable */
/* eslint-disable */
/**
 * Cash CMS API
 * Cash CMS API.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@cashcms.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CashcmsMembership
 */
export interface CashcmsMembership {
    /**
     * 
     * @type {string}
     * @memberof CashcmsMembership
     */
    description?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CashcmsMembership
     */
    features?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof CashcmsMembership
     */
    price?: string;
    /**
     * 
     * @type {string}
     * @memberof CashcmsMembership
     */
    remark?: string;
    /**
     * 
     * @type {string}
     * @memberof CashcmsMembership
     */
    tip?: string;
    /**
     * 
     * @type {string}
     * @memberof CashcmsMembership
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof CashcmsMembership
     */
    type?: string;
}

/**
 * Check if a given object implements the CashcmsMembership interface.
 */
export function instanceOfCashcmsMembership(value: object): boolean {
    return true;
}

export function CashcmsMembershipFromJSON(json: any): CashcmsMembership {
    return CashcmsMembershipFromJSONTyped(json, false);
}

export function CashcmsMembershipFromJSONTyped(json: any, ignoreDiscriminator: boolean): CashcmsMembership {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'features': json['features'] == null ? undefined : json['features'],
        'price': json['price'] == null ? undefined : json['price'],
        'remark': json['remark'] == null ? undefined : json['remark'],
        'tip': json['tip'] == null ? undefined : json['tip'],
        'title': json['title'] == null ? undefined : json['title'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function CashcmsMembershipToJSON(value?: CashcmsMembership | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'description': value['description'],
        'features': value['features'],
        'price': value['price'],
        'remark': value['remark'],
        'tip': value['tip'],
        'title': value['title'],
        'type': value['type'],
    };
}

