/* tslint:disable */
/* eslint-disable */
/**
 * Cash CMS API
 * Cash CMS API.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@cashcms.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CashcmsPost } from './CashcmsPost';
import {
    CashcmsPostFromJSON,
    CashcmsPostFromJSONTyped,
    CashcmsPostToJSON,
} from './CashcmsPost';

/**
 * 
 * @export
 * @interface CashcmsPagedResponseCashcmsPost
 */
export interface CashcmsPagedResponseCashcmsPost {
    /**
     * 
     * @type {Array<CashcmsPost>}
     * @memberof CashcmsPagedResponseCashcmsPost
     */
    data?: Array<CashcmsPost>;
    /**
     * 
     * @type {number}
     * @memberof CashcmsPagedResponseCashcmsPost
     */
    total?: number;
}

/**
 * Check if a given object implements the CashcmsPagedResponseCashcmsPost interface.
 */
export function instanceOfCashcmsPagedResponseCashcmsPost(value: object): boolean {
    return true;
}

export function CashcmsPagedResponseCashcmsPostFromJSON(json: any): CashcmsPagedResponseCashcmsPost {
    return CashcmsPagedResponseCashcmsPostFromJSONTyped(json, false);
}

export function CashcmsPagedResponseCashcmsPostFromJSONTyped(json: any, ignoreDiscriminator: boolean): CashcmsPagedResponseCashcmsPost {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(CashcmsPostFromJSON)),
        'total': json['total'] == null ? undefined : json['total'],
    };
}

export function CashcmsPagedResponseCashcmsPostToJSON(value?: CashcmsPagedResponseCashcmsPost | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(CashcmsPostToJSON)),
        'total': value['total'],
    };
}

