/* tslint:disable */
/* eslint-disable */
/**
 * Cash CMS API
 * Cash CMS API.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@cashcms.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CashcmsTag } from './CashcmsTag';
import {
    CashcmsTagFromJSON,
    CashcmsTagFromJSONTyped,
    CashcmsTagToJSON,
} from './CashcmsTag';

/**
 * 
 * @export
 * @interface CashcmsPost
 */
export interface CashcmsPost {
    /**
     * 附件下载次数
     * @type {number}
     * @memberof CashcmsPost
     */
    attachmentDownloadCount?: number;
    /**
     * 附件下载需要的积分
     * @type {number}
     * @memberof CashcmsPost
     */
    attachmentDownloadPoint?: number;
    /**
     * 分类 Id
     * @type {string}
     * @memberof CashcmsPost
     */
    categoryId?: string;
    /**
     * 分类名称
     * @type {string}
     * @memberof CashcmsPost
     */
    categoryName?: string;
    /**
     * 分类标题
     * @type {string}
     * @memberof CashcmsPost
     */
    categoryTitle?: string;
    /**
     * 内容
     * @type {string}
     * @memberof CashcmsPost
     */
    content?: string;
    /**
     * 封面文件 key
     * @type {string}
     * @memberof CashcmsPost
     */
    coverKey?: string;
    /**
     * 封面图片地址
     * @type {string}
     * @memberof CashcmsPost
     */
    coverUrl?: string;
    /**
     * 
     * @type {Date}
     * @memberof CashcmsPost
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof CashcmsPost
     */
    deletedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof CashcmsPost
     */
    id?: string;
    /**
     * 是否是草稿
     * @type {boolean}
     * @memberof CashcmsPost
     */
    isDraft?: boolean;
    /**
     * 是否是付费可见
     * @type {boolean}
     * @memberof CashcmsPost
     */
    isPaid?: boolean;
    /**
     * 是否是私密
     * @type {boolean}
     * @memberof CashcmsPost
     */
    isPrivate?: boolean;
    /**
     * 是否置顶
     * @type {boolean}
     * @memberof CashcmsPost
     */
    isTop?: boolean;
    /**
     * 是否是会员可见
     * @type {boolean}
     * @memberof CashcmsPost
     */
    isVip?: boolean;
    /**
     * 是否是会员免费
     * @type {boolean}
     * @memberof CashcmsPost
     */
    isVipFree?: boolean;
    /**
     * 付费价格
     * @type {string}
     * @memberof CashcmsPost
     */
    price?: string;
    /**
     * 标签
     * @type {Array<CashcmsTag>}
     * @memberof CashcmsPost
     */
    tags?: Array<CashcmsTag>;
    /**
     * 标题
     * @type {string}
     * @memberof CashcmsPost
     */
    title: string;
    /**
     * 
     * @type {Date}
     * @memberof CashcmsPost
     */
    updatedAt?: Date;
    /**
     * 用户 Id
     * @type {string}
     * @memberof CashcmsPost
     */
    userId?: string;
}

/**
 * Check if a given object implements the CashcmsPost interface.
 */
export function instanceOfCashcmsPost(value: object): boolean {
    if (!('title' in value)) return false;
    return true;
}

export function CashcmsPostFromJSON(json: any): CashcmsPost {
    return CashcmsPostFromJSONTyped(json, false);
}

export function CashcmsPostFromJSONTyped(json: any, ignoreDiscriminator: boolean): CashcmsPost {
    if (json == null) {
        return json;
    }
    return {
        
        'attachmentDownloadCount': json['attachmentDownloadCount'] == null ? undefined : json['attachmentDownloadCount'],
        'attachmentDownloadPoint': json['attachmentDownloadPoint'] == null ? undefined : json['attachmentDownloadPoint'],
        'categoryId': json['categoryId'] == null ? undefined : json['categoryId'],
        'categoryName': json['categoryName'] == null ? undefined : json['categoryName'],
        'categoryTitle': json['categoryTitle'] == null ? undefined : json['categoryTitle'],
        'content': json['content'] == null ? undefined : json['content'],
        'coverKey': json['coverKey'] == null ? undefined : json['coverKey'],
        'coverUrl': json['coverUrl'] == null ? undefined : json['coverUrl'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'deletedAt': json['deletedAt'] == null ? undefined : (new Date(json['deletedAt'])),
        'id': json['id'] == null ? undefined : json['id'],
        'isDraft': json['isDraft'] == null ? undefined : json['isDraft'],
        'isPaid': json['isPaid'] == null ? undefined : json['isPaid'],
        'isPrivate': json['isPrivate'] == null ? undefined : json['isPrivate'],
        'isTop': json['isTop'] == null ? undefined : json['isTop'],
        'isVip': json['isVip'] == null ? undefined : json['isVip'],
        'isVipFree': json['isVipFree'] == null ? undefined : json['isVipFree'],
        'price': json['price'] == null ? undefined : json['price'],
        'tags': json['tags'] == null ? undefined : ((json['tags'] as Array<any>).map(CashcmsTagFromJSON)),
        'title': json['title'],
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'userId': json['userId'] == null ? undefined : json['userId'],
    };
}

export function CashcmsPostToJSON(value?: CashcmsPost | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'attachmentDownloadCount': value['attachmentDownloadCount'],
        'attachmentDownloadPoint': value['attachmentDownloadPoint'],
        'categoryId': value['categoryId'],
        'categoryName': value['categoryName'],
        'categoryTitle': value['categoryTitle'],
        'content': value['content'],
        'coverKey': value['coverKey'],
        'coverUrl': value['coverUrl'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'deletedAt': value['deletedAt'] == null ? undefined : ((value['deletedAt']).toISOString()),
        'id': value['id'],
        'isDraft': value['isDraft'],
        'isPaid': value['isPaid'],
        'isPrivate': value['isPrivate'],
        'isTop': value['isTop'],
        'isVip': value['isVip'],
        'isVipFree': value['isVipFree'],
        'price': value['price'],
        'tags': value['tags'] == null ? undefined : ((value['tags'] as Array<any>).map(CashcmsTagToJSON)),
        'title': value['title'],
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
        'userId': value['userId'],
    };
}

