/* tslint:disable */
/* eslint-disable */
/**
 * Cash CMS API
 * Cash CMS API.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@cashcms.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CashcmsPostAttachmentRecord
 */
export interface CashcmsPostAttachmentRecord {
    /**
     * 
     * @type {Date}
     * @memberof CashcmsPostAttachmentRecord
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof CashcmsPostAttachmentRecord
     */
    deletedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof CashcmsPostAttachmentRecord
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof CashcmsPostAttachmentRecord
     */
    postId?: string;
    /**
     * 下载token
     * @type {string}
     * @memberof CashcmsPostAttachmentRecord
     */
    token?: string;
    /**
     * 
     * @type {Date}
     * @memberof CashcmsPostAttachmentRecord
     */
    updatedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof CashcmsPostAttachmentRecord
     */
    userId?: string;
}

/**
 * Check if a given object implements the CashcmsPostAttachmentRecord interface.
 */
export function instanceOfCashcmsPostAttachmentRecord(value: object): boolean {
    return true;
}

export function CashcmsPostAttachmentRecordFromJSON(json: any): CashcmsPostAttachmentRecord {
    return CashcmsPostAttachmentRecordFromJSONTyped(json, false);
}

export function CashcmsPostAttachmentRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): CashcmsPostAttachmentRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'deletedAt': json['deletedAt'] == null ? undefined : (new Date(json['deletedAt'])),
        'id': json['id'] == null ? undefined : json['id'],
        'postId': json['postId'] == null ? undefined : json['postId'],
        'token': json['token'] == null ? undefined : json['token'],
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'userId': json['userId'] == null ? undefined : json['userId'],
    };
}

export function CashcmsPostAttachmentRecordToJSON(value?: CashcmsPostAttachmentRecord | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'deletedAt': value['deletedAt'] == null ? undefined : ((value['deletedAt']).toISOString()),
        'id': value['id'],
        'postId': value['postId'],
        'token': value['token'],
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
        'userId': value['userId'],
    };
}

