/* tslint:disable */
/* eslint-disable */
/**
 * Cash CMS API
 * Cash CMS API.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@cashcms.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CashcmsCredentials
 */
export interface CashcmsCredentials {
    /**
     * 临时证书密钥ID
     * @type {string}
     * @memberof CashcmsCredentials
     */
    tmpSecretId?: string;
    /**
     * 临时证书密钥Key
     * @type {string}
     * @memberof CashcmsCredentials
     */
    tmpSecretKey?: string;
    /**
     * token
     * @type {string}
     * @memberof CashcmsCredentials
     */
    token?: string;
}

/**
 * Check if a given object implements the CashcmsCredentials interface.
 */
export function instanceOfCashcmsCredentials(value: object): boolean {
    return true;
}

export function CashcmsCredentialsFromJSON(json: any): CashcmsCredentials {
    return CashcmsCredentialsFromJSONTyped(json, false);
}

export function CashcmsCredentialsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CashcmsCredentials {
    if (json == null) {
        return json;
    }
    return {
        
        'tmpSecretId': json['tmpSecretId'] == null ? undefined : json['tmpSecretId'],
        'tmpSecretKey': json['tmpSecretKey'] == null ? undefined : json['tmpSecretKey'],
        'token': json['token'] == null ? undefined : json['token'],
    };
}

export function CashcmsCredentialsToJSON(value?: CashcmsCredentials | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'tmpSecretId': value['tmpSecretId'],
        'tmpSecretKey': value['tmpSecretKey'],
        'token': value['token'],
    };
}

